#!/bin/bash -ex
cd ~/klipper && make KCONFIG_CONFIG=tools.config clean && make KCONFIG_CONFIG=tools.config && cd -
~/katapult/scripts/flashtool.py -i can0 -f ~/klipper/out/klipper.bin -u 3e62ec359682 && cd -
